config/routes.rb
Spree::Core::Engine.routes.draw do

  resources :orders do
    post 'postback', :to => 'orders#postback', :as => :postback
  end

  namespace :admin do
    resources :banks

    resources :users do
      resources :bank_accounts do
        post 'revalidate', :on => :member
        post 'check_pagarme', :on => :member
      end
    end
  end
  
end

app/views/spree/admin/payments/source_views/_pagarmemethod.html.erb
<% content_for :page_actions do %>

<% end %>

<% pagarme_payment = payment.pagarme_payment %>
<fieldset data-hook="creditcard">
	<legend>Pagar.me</legend>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><%= t('pagarme.payment_url') %></h3>
		</div>
		<table class="table table-condensed table-bordered">
			<tr>
				<td>
					<% method = pagarme_payment.payment_method if pagarme_payment %>
					<% if method && pagarme_payment.within_expiration_date? %>
						<%= link_to t("pagarme.reprint_boleto"), pagarme_payment.boleto_url %>
					<% elsif method %>
						<%= link_to t("pagarme.retry_payment"), order_path(payment.order) %>
					<% else method.nil? %>
						<%= t('pagarme.payment_url_doesnt_exist') %>
					<% end %>
				</td>
			</tr>
		</table>
	</div>


	<% transaction = pagarme_payment.transaction %>
	<% if transaction %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= Spree.t(:summary) %></h3>
			</div>
			<table class="table table-condensed table-bordered">
				<tr>
					<th width="35%"><%= Spree.t(:created_at) %>:</th>
					<td><%= transaction.date_created.to_datetime.strftime("%d/%m/%Y - %H:%M:%S") %></td>
				</tr>
				<tr>
					<th><%= t('pagarme.method') %>:</th>
					<td>
						<%= t("pagarme.method_#{transaction.payment_method}") %>
						<% if transaction.payment_method == "credit_card" %>
							(<%= transaction.card_brand %>)
						<% elsif transaction.payment_method == "boleto" %>
							(<%= t('pagarme.valid_until') %> <%= transaction.boleto_expiration_date.to_datetime.strftime("%d/%m/%Y") %>)
						<% end %>
					</td>
				</tr>
				<tr>
					<th><%= Spree.t(:state) %>:</th>
					<td>
						<span class="label <%= t("pagarme.states.class.#{transaction.status}") %>"><%= t("pagarme.states.#{transaction.status}") %></span>
						<% if transaction.status == 'refused' %>
							(<%= transaction.status_reason %>)
						<% end %>
						<%# t("pagseguro_status.#{PagSeguro::Transaction.status_for(notification.status.to_i)}") %>
					</td>
				</tr>
				<tr>
					<th>Transaction ID:</th>
					<td><%= transaction.id %></td>
				</tr>
				<tr>
					<th><%= t('pagarme.amount_paid') %>:</th>
					<td><%= Spree::Money.new( (transaction.paid_amount.to_f/100) , { :currency=> 'BRL' }) %></td>
				</tr>
				<tr>
					<th><%= t('pagarme.last_update') %>:</th>
					<td><%= transaction.date_updated.to_datetime.strftime("%d/%m/%Y - %H:%M:%S") if transaction.date_updated %></td>
				</tr>
			</table>
		</div>
	<% else %>
		<table class="table table-condensed table-bordered">
			<tr>
				<td><%= t('pagarme.errors.transaction_not_found') %></td>
			</tr>
		</table>
	<% end %>

</fieldset>